### AQUI SE SIMULA LA REQ QUE ENVIA EL CLIENTE

###recuperar todas las peliculas 
GET http://localhost:1234/movies

###RECUPERAR PELICULAS POR ID
GET http://localhost:1234/movies/5ad1a235-0d9c-410a-b32b-220d91689a08

### RECUPERAR PELICULAS POR GENERO
GET http://localhost:1234/movies?genre=DRAMA 

### CREAMOS LA PELICULA
POST http://localhost:1234/movies
Content-Type: application/json

{
  "title": "Pulp Fiction",
  "year": 1994,
  "director": "Quentin Tarantino",
  "duration": 154,
  "poster": "https://www.themoviedb.org/t/p/original/vQWk5YBFWF4bZaofAbv0tShwBvQ.jpg",
  "genre": ["Crime", "Drama"],
  "rate": 8.9
}

### ACTUALIZAR UN DATO E LA PELICULA
PATCH http://localhost:1234/movies/dcdd0fad-a94c-4810-8acc-5f108d3b18c3
Content-Type: application/json

{
  "director" : "Luis Salinas",
  "year" : 2005
}